export const domElements = {
  addButton: document.getElementById("add"),
  imageInput: document.getElementById("image-input"),
  imagePreview: document.getElementById("image-preview"),
  canvas: document.getElementById("canvas"),
  ctx: document.getElementById("canvas").getContext("2d"),
  colorDisplay: document.getElementById("color-display"),
  pickedColor: document.getElementById("picked-color"),
  label: document.getElementById("label"),
  tools: document.querySelectorAll("#tools > *"),
  toolSection: document.getElementById("tools"),
  colorSwitcher: document.getElementById("color-switcher"),
  cropSwitcher: document.getElementById("crop-switcher"),
  filterSwitcher: document.getElementById("filter-switcher"),
  filterRange: document.getElementById("filter-range"),
  contrast: document.getElementById("contrast"),
  brightness: document.getElementById("brightness"),
  saturation: document.getElementById("saturation"),
};
